# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 48822815c0d00968816237a9b6abb6e2b3b5243bc677a63731e0fd7e494cec8751c9b1c5e3c2883d2e023d272430e2fe95a590627bac11eca82bdeea05c50fed

test:
  secret_key_base: e23f15a8317f2260014b3e239fcb25ae380cdd9d572dfc4b2698f42a16b4c94b08af2944690bc395f35db902c7dc6799e15451f484184f5e19bc754b2dc466b0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
